name: 📚 Epic/Storia
description: Crea una storia che raggruppa multiple issue
title: "[EPIC] "
labels: ["epic", "planning"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 📚 Epic/Storia
        Le Epic sono macro-funzionalità che raggruppano più issue correlate. Descrivi l'obiettivo generale e poi elenca tutte le issue che compongono questa storia.
        
        ### 📝 Convenzioni per il titolo
        - **Epic**: `[EPIC] Nome della storia principale`
        - Esempi: `[EPIC] Sistema di Autenticazione`, `[EPIC] Dashboard Utente`, `[EPIC] Sistema di Pagamenti`

  - type: textarea
    id: epic-description
    attributes:
      label: 🎯 Descrizione della Storia
      description: Qual è l'obiettivo generale di questa Epic?
      placeholder: |
        Questa Epic prevede l'implementazione completa del sistema di autenticazione per permettere agli utenti di registrarsi, effettuare login e gestire il proprio profilo...
    validations:
      required: true

  - type: textarea
    id: business-value
    attributes:
      label: 💼 Valore di Business
      description: Perché questa Epic è importante? Che benefici porta?
      placeholder: |
        - Permette agli utenti di avere un'esperienza personalizzata
        - Aumenta la sicurezza dell'applicazione
        - Abilita funzionalità premium per utenti registrati
    validations:
      required: true

  - type: textarea
    id: user-personas
    attributes:
      label: 👥 Personas Coinvolte
      description: Chi sono gli utenti che beneficeranno di questa Epic?
      placeholder: |
        - **Utente Guest**: Vuole registrarsi per accedere a funzionalità avanzate
        - **Utente Registrato**: Vuole accedere al suo account in modo sicuro
        - **Amministratore**: Vuole gestire gli utenti del sistema

  - type: dropdown
    id: epic-priority
    attributes:
      label: 📊 Priorità Epic
      description: Quanto è importante questa Epic?
      options:
        - "🔴 Critica - Must have per il release"
        - "🟠 Alta - Importante per il successo del prodotto"
        - "🟡 Media - Nice to have, valore aggiunto"
        - "🟢 Bassa - Futura iterazione"
    validations:
      required: true

  - type: dropdown
    id: epic-size
    attributes:
      label: 📏 Dimensione Stimata
      description: Quanto lavoro prevedi per questa Epic?
      options:
        - "🟢 Piccola - 1-2 settimane (3-8 issue)"
        - "🟡 Media - 3-4 settimane (8-15 issue)"
        - "🟠 Grande - 1-2 mesi (15-25 issue)"
        - "🔴 Molto Grande - 2+ mesi (25+ issue)"
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Criteri di Accettazione Epic
      description: Quando questa Epic sarà considerata completata?
      placeholder: |
        - [ ] Gli utenti possono registrarsi con email e password
        - [ ] Gli utenti possono effettuare login
        - [ ] Gli utenti possono recuperare la password
        - [ ] Gli utenti possono modificare il profilo
        - [ ] Il sistema è sicuro e protetto da attacchi comuni
        - [ ] Tutti i test sono implementati e passano
    validations:
      required: true

  - type: textarea
    id: technical-notes
    attributes:
      label: 🔧 Note Tecniche
      description: Considerazioni tecniche, architettura, dipendenze
      placeholder: |
        - Tecnologie: JWT, bcrypt, React Context
        - Dipendenze esterne: Libreria di validazione email
        - Database: Nuove tabelle users, sessions
        - API: Endpoints /auth/login, /auth/register, /auth/profile

  - type: textarea
    id: issues-list
    attributes:
      label: 📋 Lista Issue da Creare
      description: |
        Elenca tutte le issue che compongono questa Epic. Usa questo formato:
        - **[FEAT] Nome issue** - Breve descrizione (Frontend/Backend)
      placeholder: |
        ### 🎨 Frontend Issues
        - **[FEAT] Creazione vista Login** - Componente per form di login
        - **[FEAT] Creazione vista Register** - Componente per registrazione utente  
        - **[FEAT] Creazione vista Profilo** - Pagina per modificare dati utente
        - **[FEAT] Implementazione validazione form** - Validazioni client-side
        
        ### ⚙️ Backend Issues  
        - **[FEAT] API endpoint login** - Endpoint POST /auth/login
        - **[FEAT] API endpoint register** - Endpoint POST /auth/register
        - **[FEAT] Middleware autenticazione** - JWT middleware per proteggere route
        - **[FEAT] Utils password hashing** - Funzioni per bcrypt
        
        ### 🗄️ Database Issues
        - **[TASK] Schema tabella users** - Creazione migrazione tabella utenti
        - **[TASK] Schema tabella sessions** - Gestione sessioni utente
        
        ### 🧪 Testing Issues
        - **[TASK] Test unitari API auth** - Test per tutti gli endpoint
        - **[TASK] Test E2E flusso autenticazione** - Test completo del flusso
    validations:
      required: true

  - type: textarea
    id: mockups-design
    attributes:
      label: 🎨 Design e Mockup
      description: Link a design, mockup o wireframe
      placeholder: |
        - Link Figma: https://figma.com/...
        - Riferimenti UI: Link a design system o esempi
        - Note di design: Colori, typography, spacing

  - type: textarea
    id: dependencies
    attributes:
      label: 🔗 Dipendenze
      description: Altre Epic o issue che devono essere completate prima
      placeholder: |
        - Epic #12: Setup Base del Progetto (deve essere completata)
        - Issue #45: Configurazione Database (prerequisito)

  - type: textarea
    id: definition-of-done
    attributes:
      label: ✅ Definition of Done
      description: Checklist generale per tutte le issue di questa Epic
      placeholder: |
        Per ogni issue di questa Epic:
        - [ ] Codice sviluppato e funzionante
        - [ ] Test unitari scritti e passanti  
        - [ ] Test di integrazione (se necessari)
        - [ ] Code review completata
        - [ ] Documentazione aggiornata
        - [ ] Deploy su ambiente di staging
        - [ ] Validazione con stakeholder
