version: "3.8"
services:
  backend:
    build:
      context: ./serve_BE
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/serve_db
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: serve_db
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./serve-fe
    ports:
      - "8080:8080"
