services:
  db:
    image: postgres:15
    container_name: serve_postgres
    restart: always
    environment:
      POSTGRES_USER: serveuser
      POSTGRES_PASSWORD: servepass
      POSTGRES_DB: servedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase
    depends_on:
      - db
    volumes:
      - ./liquibase/changelog:/liquibase/changelog
      - ./liquibase/liquibase.properties:/liquibase/liquibase.properties
    working_dir: /liquibase/changelog
    command: >
      --defaultsFile=/liquibase/liquibase.properties update

  backend:
    build: .
    container_name: serve_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: serveuser
      DB_PASSWORD: servepass
      DB_NAME: servedb
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  postgres_data:
