version: '3.8'
services:
  frontend:
    build:
      context: ./serve-fe
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_API_URL=http://backend:3000  # URL del backend
    networks:
      - frontend_network
